[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "APP_URL"
  NODE_VERSION = "18"

[functions]
  timeout = 26

[[redirects]]
  from = "/"
  to = "/login.html"
  status = 302

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200
