[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/"
  to = "/login.html"
  status = 302
  conditions = {Cookie = ["!sb-access-token"]}

[[redirects]]
  from = "/app"
  to = "/app.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200
